const CATEGORIES = {
  ON: 'CATEGORIES_ON',
  OFF: 'CATEGORIES_OFF',
};

const PRODUCT_INTRO_NOTICE = {
  ON: 'PRODUCT_INTRO_NOTICE_ON',
  OFF: 'PRODUCT_INTRO_NOTICE_OFF',
};

export { CATEGORIES, PRODUCT_INTRO_NOTICE };
